AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Exclude:
    - 'lib/tl1/platforms/bti.rb'
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/tl1/command_spec.rb'

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
